### ISSUE TITLE
Error in 1-load-OMOP

### ISSUE THREAD

**Issue by m-francisco** [kpwhri/HCSRN-VDW-to-OHDSI-OMOP#1]
Error in 1-load-OMOP.sas
- line 54:  calls &_rcm_pos (dat.rcm_utl_pos).  Not finding the step where this dataset was created.  Did I miss something in the set-up?

**Comment by weeksjm** [comment]
Thanks Melanie,  the POS value should be getting generated from the enc_subtype, but our local code uses a POS code that is getting pulled from our claims data.  I'll double check and make sure that this is working correctly.
